import React,{ createContext, useContext, useState, ReactNode} from "react";
export type Language = "fr" | "ar";
interface LanguageContextProps{
    language: Language;
    setLanguage:(lang: Language) => void;
    toggleLanguage: () => void;
    translations: Record<Language, Record<string, string>>;
}
const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const translations = {
    fr: {
        welcome: "Bienvenue sur IREPAIR",
        introTitle: "Commençons avec nous",
        introSubtitle: "Trouvez ou vendez facilement des pièces automobiles. Proposez vos services de mécanique et développez votre activité en toute simplicité",
        login: "Connexion",
        register: "S'inscrire",
        loginTitle: "Bienvenue de nouveau",
        loginSubtitle: "Connectez-vous avec votre numéro de téléphone et mot de passe",
        phonePlaceholder: "+21* ** *** ***",
        passwordPlaceholder: "Entrez le mot de passe",
        forgotPassword: "Mot de passe oublié ?",
        garageDetails:"Détails du garage",
        garageNamePlaceholder:"Nom du garage",
        geographicZonePlaceholder:"Zone géographique",
        geolocationPlaceholder:"Emplacement",
        managerDetails:"Détails du responsable",
        managerNamePlaceholder:"Nom du responsable",
        emailPlaceholder:"Adresse e-mail",
        servicesTitle:"Services",
        passwordTitle:"Mot de passe",
        back: "Retour",
        signup: "S'inscrire",
        next:"Suivant",
        locationPicked: "Emplacement sélectionné",
        pickOnMap: "Choisir sur la carte",
        invalidEmail: "Adresse e-mail invalide",
        invalidGeolocation: "Emplacement invalide",
        noAccount: "Vous n'avez pas de compte ?",
        wrongCredentials: "Identifiants incorrects",
        verifyTitle: "Vérifiez votre téléphone",
        verifySubtitle: "Entrez le code à 6 chiffres envoyé à votre numéro de téléphone",
        codePlaceholder: "Entrez le code à 6 chiffres",
        verify: "Vérifier",
        resendCode: "Renvoyer le code",
        resendFailed: "Échec de l'envoi du code. Veuillez réessayer.",
        invalidCode: "Code de vérification invalide",
        unexpectedError: "Une erreur inattendue s'est produite. Veuillez réessayer.",
        noPhoneNumber: "Aucun numéro de téléphone trouvé. Veuillez recommencer l'inscription.",
        forgotPasswordTitle: "Mot de passe oublié",
        forgotPasswordSubtitle: "Entrez votre numéro de téléphone pour recevoir un code de réinitialisation",
        sendCode: "Envoyer le code",
        resetPasswordTitle: "Réinitialiser le mot de passe",
        resetPasswordSubtitle: "Entrez le code et votre nouveau mot de passe",
        newPasswordPlaceholder: "Entrez le nouveau mot de passe",
        resetPassword: "Réinitialiser le mot de passe",
        backToLogin: "Retour à",
        // Dashboard translations
        dashboard: "Tableau de bord",
        serviceManagement: "Gestion des services",
        myServices: "Mes services",
        serviceRequests: "Demandes de service",
        partsInventory: "Inventaire des pièces",
        appointments: "Rendez-vous",
        profile: "Profil",
        logout: "Déconnexion",
        profileTitle: "Profil du mécanicien",
        mechanicName: "Ahmed Benali",
        specialty: "Spécialité : Réparation et entretien automobile",
        location: "Lieu : Alger, Algérie",
        contact: "Contact : +213 123 456 789",
        editProfile: "Modifier le profil",
        quickActions: "Actions rapides",
        garageName: "Nom du garage",
        managerName: "Nom du responsable",
        garageLocation: "Emplacement du garage",
        services: "Services offerts",
        mapLocation: "Localisation",
        fillAllFields: "Veuillez remplir tous les champs",
        save: "Sauvegarder",
        cancel: "Annuler",
        editProfileTitle: "Modifier le profil",
        editProfileSubtitle: "Mettez à jour les détails de votre profil ci-dessous",
        namePlaceholder: "Entrez le nom",
        // Calendar specific translations
        success: "Succès",
        error: "Erreur",
        info: "Information",
        complete: "Terminer",
        basicInformation: "Informations de base",
        contactInformation: "Informations de contact",
        garageProfile: "Profil du garage",
        updateGarageInfo: "Mettez à jour les informations de votre garage",
        selectServices: "Sélectionnez les services que votre garage propose",
        servicesOffered: "Services offerts",
        contactNumber: "Numéro de contact",
        email: "E-mail",
        saveChanges: "Sauvegarder les modifications",
        successProfileUpdate: "Profil mis à jour avec succès !",
        ok: "OK",
        profileUpdateFailed: "Échec de la mise à jour du profil. Veuillez réessayer.",
        
        // Parts Request translations
        requestPart: "Demander une pièce",
        vehicleVinNumber: "Numéro VIN du véhicule",
        enterVinPlaceholder: "Entrez le VIN (17 caractères)",
        category: "Catégorie",
        selectCategory: "Sélectionner la catégorie",
        chooseCategory: "Choisir une catégorie",
        subCategory: "Sous-catégorie",
        selectSubCategory: "Sélectionner la sous-catégorie",
        chooseSubCategory: "Choisir une sous-catégorie",
        item: "Article",
        selectItem: "Sélectionner l'article",
        chooseItem: "Choisir un article",
        addPhotoOptional: "Ajouter une photo (optionnel)",
        photoAdded: "Photo ajoutée",
        tapToChangePhoto: "Appuyez pour changer la photo",
        tapToAddPhoto: "Appuyez pour ajouter une photo",
        quantity: "Quantité",
        urgency: "Urgence",
        low: "Faible",
        medium: "Moyen",
        high: "Élevé",
        additionalNotes: "Notes supplémentaires",
        additionalInfo: "Informations supplémentaires...",
        createRequest: "Créer la demande",
        requestHelpText: "Après avoir soumis votre demande, les utilisateurs ipiece ayant des véhicules correspondants seront notifiés et pourront vous contacter via le système de messagerie ou par téléphone.",
        
        // Success/Error messages
        requestCreated: "Demande créée",
        requestCreatedMessage: "Votre demande de pièce a été créée avec succès",
        sessionExpired: "Session expirée",
        sessionExpiredMessage: "Votre session a expiré, veuillez vous reconnecter",
        invalidRequest: "Demande invalide",
        invalidRequestMessage: "La demande est invalide, veuillez vérifier les données",
        partNotFound: "Pièce non trouvée",
        partNotFoundMessage: "La pièce demandée n'a pas été trouvée",
        unableToCreateRequestMessage: "Impossible de créer la demande, veuillez réessayer",
        
        // Image upload translations
        uploadImage: "Télécharger l'image",
        retake: "Reprendre",
        camera: "Caméra",
        gallery: "Galerie",
        done: "Terminé",
        skipPhoto: "Ignorer la photo",
        uploadingImage: "Téléchargement de l'image...",
        preview: "Aperçu",
        uploaded: "Téléchargé",
        
        // Modal titles
        loadingCategories: "Chargement des catégories...",
        loadingSubcategories: "Chargement des sous-catégories...",
        loadingItems: "Chargement des articles...",
        noCategoriesFound: "Aucune catégorie trouvée",
        noSubcategoriesFound: "Aucune sous-catégorie trouvée",
        noItemsFound: "Aucun article trouvé",
        
        // Dashboard additional translations
        ads: "Publicités",
        new: "Nouveau",
        specialOffer: "Offre Spéciale",
        discoverMore: "Découvrez plus",
        hello: "Bonjour",
        manageServices: "Gérer vos services",
        viewAllServices: "Voir tous les services",
        planAndManage: "Planifier & gérer",
        trackYourRequests: "Suivre vos demandes",
        
        // My Services translations
        myServicesTitle: "Mes services",
        addService: "Ajouter un service",
        noServices: "Aucun service",
        tapToAddNewService: "Appuyez sur + pour ajouter un nouveau service",
        loadingServices: "Chargement...",
        serviceType: "Type de service",
        serviceName: "Nom du service",
        serviceDescription: "Description",
        price: "Prix",
        duration: "Durée",
        addNewService: "Ajouter un service",
        editService: "Modifier le service",
        deleteService: "Supprimer le service",
        confirmDelete: "Êtes-vous sûr de vouloir supprimer",
        delete: "Supprimer",
        edit: "Modifier",
        active: "Actif",
        inactive: "Inactif",
        selectServiceType: "Sélectionner le type de service",
        serviceNameRequired: "Le nom du service est requis",
        priceRequired: "Le prix est requis",
        durationRequired: "La durée est requise",
        serviceCreated: "Service créé avec succès",
        serviceUpdated: "Service mis à jour avec succès",
        serviceDeleted: "Service supprimé avec succès",
        saving: "Enregistrement...",
        update: "Mettre à jour",
        add: "Ajouter",
        hours: "heures",
        hour: "heure",
        days: "jours",
        day: "jour",
        
        // Parts Requests translations
        partsRequests: "Demandes de pièces",
        allRequests: "Toutes",
        pending: "En attente",
        accepted: "Accepté",
        rejected: "Rejeté",
        completed: "Terminé",
        all: "Toutes",
        noRequests: "Aucune demande",
        noRequestsDescription: "Vous n'avez encore fait aucune demande de pièces. Créez votre première demande pour vous connecter avec des fournisseurs.",
        createRequest: "Créer une demande",
        requestVisibility: "Visibilité de la demande",
        views: "vues",
        suppliersViewed: "fournisseurs ont vu cela",
        interested: "intéressé",
        contactAttempts: "tentatives de contact",
        acceptedBySupplier: "Accepté par le fournisseur",
        unknownSupplier: "Fournisseur inconnu",
        chat: "Chat",
        estimatedDelivery: "Livraison estimée",
        vehicle: "Véhicule",
        year: "Année",
        fuel: "Carburant",
        engine: "Moteur",
        licensePlate: "Plaque d'immatriculation",
        vin: "VIN",
        color: "Couleur",
        mileage: "Kilométrage",
        quantity: "Qté",
        message: "Message",
        unknownPart: "Pièce inconnue",
        loadingRequests: "Chargement des demandes...",
        
        // Edit Profile translations
        editProfileTitle: "Modifier le profil",
        garageProfile: "Profil du garage",
        updateGarageInfo: "Mettez à jour les informations de votre garage",
        basicInformation: "Informations de base",
        contactInformation: "Informations de contact",
        garageName: "Nom du garage",
        managerName: "Nom du responsable",
        location: "Emplacement",
        contactNumber: "Numéro de contact",
        email: "E-mail",
        servicesOffered: "Services offerts",
        selectServicesDescription: "Sélectionnez les services que votre garage propose",
        saveChanges: "Sauvegarder les modifications",
        cancel: "Annuler",
        fillAllFields: "Veuillez remplir tous les champs",
        selectServices: "Veuillez sélectionner au moins un service",
        successProfileUpdate: "Profil mis à jour avec succès !",
        profileUpdateFailed: "Échec de la mise à jour du profil. Veuillez réessayer.",
        garageNamePlaceholder: "Entrez le nom du garage",
        managerNamePlaceholder: "Entrez le nom du responsable",
        locationPlaceholder: "Entrez l'emplacement",
        contactPlaceholder: "Entrez le numéro de contact",
        emailPlaceholder: "Entrez l'e-mail",
        
        // Additional translations
        confirmLogout: "Êtes-vous sûr de vouloir vous déconnecter ?",
        spareParts: "Demander des pièces",
        myPartsRequests: "Mes demandes de pièces"
    },
    ar: {
        welcome: "مرحبًا بكم في IREPAIR",
        introTitle: "لنبدأ معًا",
        introSubtitle: "ابحث أو بع بسهولة قطع غيار السيارات. قدّم خدماتك في الميكانيك وطوّر عملك بكل سهولة.",
        login: "تسجيل الدخول",
        register: "إنشاء حساب",
        loginTitle:"مرحبًا بعودتك",
        loginSubtitle: "سجّل دخولك باستخدام رقم هاتفك وكلمة المرور",
        phonePlaceholder: "أدخل رقم الهاتف",
        passwordPlaceholder: "أدخل كلمة المرور",
        forgotPassword: "هل نسيت كلمة المرور؟",
        garageDetails: "تفاصيل الورشة",
        garageNamePlaceholder: "اسم الورشة",
        geographicZonePlaceholder: "المنطقة الجغرافية",
        geolocationPlaceholder: "الموقع الجغرافي",
        managerDetails:"تفاصيل المدير",
        managerNamePlaceholder:"اسم المدير",
        emailPlaceholder:"البريد الإلكتروني",
        servicesTitle:"الخدمات",
        passwordTitle:"كلمة المرور",
        back:"الرجوع",
        signup:"انشاء حساب",
        next:"التالي",
        locationPicked: "الموقع المحدد",
        pickOnMap: "اختر على الخريطة",
        invalidEmail: "البريد الإلكتروني غير صالح",
        invalidGeolocation: "الموقع الجغرافي غير صالح",
        noAccount: "ليس لديك حساب؟",
        wrongCredentials: "بيانات الاعتماد غير صحيحة",
        verifyTitle: "تأكيد رقم الهاتف",
        verifySubtitle: "أدخل رمز التحقق المكون من 6 أرقام المرسل إلى رقم هاتفك",
        codePlaceholder: "أدخل رمز التحقق المكون من 6 أرقام",
        verify: "تأكيد",
        resendCode: "إعادة إرسال الرمز",
        resendFailed: "فشل في إرسال الرمز. حاول مرة أخرى.",
        invalidCode: "رمز التحقق غير صحيح",
        unexpectedError: "حدث خطأ غير متوقع. حاول مرة أخرى.",
        noPhoneNumber: "لم يتم العثور على رقم هاتف. يرجى إعادة التسجيل.",
        forgotPasswordTitle: "نسيت كلمة المرور",
        forgotPasswordSubtitle: "أدخل رقم هاتفك لاستلام رمز إعادة التعيين",
        sendCode: "إرسال الرمز",
        resetPasswordTitle: "إعادة تعيين كلمة المرور",
        resetPasswordSubtitle: "أدخل الرمز وكلمة المرور الجديدة",
        newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
        resetPassword: "إعادة تعيين كلمة المرور",
        backToLogin: "العودة إلى",
        // Dashboard translations
        dashboard: "لوحة التحكم",
        serviceManagement: "إدارة الخدمات",
        myServices: "خدماتي",
        serviceRequests: "طلبات الخدمة",
        partsInventory: "مخزون القطع",
        appointments: "المواعيد",
        profile: "الملف الشخصي",
        logout: "تسجيل الخروج",
        profileTitle: "ملف الميكانيكي",
        mechanicName: "أحمد بن علي",
        specialty: "التخصص: إصلاح وصيانة السيارات",
        location: "الموقع: الجزائر، الجزائر",
        contact: "الاتصال: +213 123 456 789",
        editProfile: "تعديل الملف الشخصي",
        quickActions: "الإجراءات السريعة",
        garageName: "اسم الورشة",
        managerName: "اسم المدير",
        garageLocation: "موقع الورشة",
        services: "الخدمات المقدمة",
        mapLocation: "الموقع الجغرافي",
        fillAllFields: "يرجى ملء جميع الحقول",
        save: "حفظ",
        cancel: "إلغاء",
        editProfileTitle: "تعديل الملف الشخصي",
        editProfileSubtitle: "قم بتحديث تفاصيل ملفك الشخصي أدناه",
        namePlaceholder: "أدخل الاسم",
        // Calendar specific translations
        success: "نجاح",
        error: "خطأ",
        info: "معلومات",
        complete: "إكمال",
        basicInformation: "معلومات أساسية",
        contactInformation: "معلومات الاتصال",
        garageProfile: "ملف الورشة",
        updateGarageInfo: "قم بتحديث معلومات ورشتك",
        selectServices: "حدد الخدمات التي تقدمها ورشتك",
        servicesOffered: "الخدمات المقدمة",
        contactNumber: "رقم الاتصال",
        email: "البريد الإلكتروني",
        saveChanges: "حفظ التغييرات",
        successProfileUpdate: "تم تحديث الملف الشخصي بنجاح!",
        ok: "موافق",
        profileUpdateFailed: "فشل في تحديث الملف الشخصي. حاول مرة أخرى.",
        
        // Parts Request translations
        requestPart: "طلب قطعة غيار",
        vehicleVinNumber: "رقم هوية المركبة (VIN)",
        enterVinPlaceholder: "أدخل رقم VIN (17 حرفًا)",
        category: "الفئة",
        selectCategory: "اختر الفئة",
        chooseCategory: "اختر فئة",
        subCategory: "الفئة الفرعية",
        selectSubCategory: "اختر الفئة الفرعية",
        chooseSubCategory: "اختر فئة فرعية",
        item: "العنصر",
        selectItem: "اختر العنصر",
        chooseItem: "اختر عنصرًا",
        addPhotoOptional: "إضافة صورة (اختياري)",
        photoAdded: "تمت إضافة الصورة",
        tapToChangePhoto: "اضغط لتغيير الصورة",
        tapToAddPhoto: "اضغط لإضافة صورة",
        quantity: "الكمية",
        urgency: "الأولوية",
        low: "منخفضة",
        medium: "متوسطة", 
        high: "عالية",
        additionalNotes: "ملاحظات إضافية",
        additionalInfo: "معلومات إضافية...",
        createRequest: "إنشاء الطلب",
        requestHelpText: "بعد إرسال طلبك، سيتم إشعار مستخدمي ipiece الذين لديهم مركبات متطابقة ويمكنهم الاتصال بك من خلال نظام الرسائل أو الهاتف.",
        
        // Success/Error messages
        requestCreated: "تم إنشاء الطلب",
        requestCreatedMessage: "تم إنشاء طلب القطعة بنجاح",
        sessionExpired: "انتهت الجلسة",
        sessionExpiredMessage: "انتهت جلستك، يرجى تسجيل الدخول مرة أخرى",
        invalidRequest: "طلب غير صالح",
        invalidRequestMessage: "الطلب غير صالح، يرجى التحقق من البيانات",
        partNotFound: "القطعة غير موجودة",
        partNotFoundMessage: "القطعة المطلوبة غير موجودة",
        unableToCreateRequestMessage: "تعذر إنشاء الطلب، يرجى المحاولة مرة أخرى",
        
        // Image upload translations
        uploadImage: "رفع الصورة",
        retake: "إعادة التقاط",
        camera: "الكاميرا",
        gallery: "المعرض",
        done: "تم",
        skipPhoto: "تخطي الصورة",
        uploadingImage: "جاري رفع الصورة...",
        preview: "معاينة",
        uploaded: "تم الرفع",
        
        // Modal titles
        loadingCategories: "جاري تحميل الفئات...",
        loadingSubcategories: "جاري تحميل الفئات الفرعية...",
        loadingItems: "جاري تحميل العناصر...",
        noCategoriesFound: "لم يتم العثور على فئات",
        noSubcategoriesFound: "لم يتم العثور على فئات فرعية",
        noItemsFound: "لم يتم العثور على عناصر",
        
        // Dashboard additional translations
        ads: "إعلانات",
        new: "جديد",
        specialOffer: "عرض خاص",
        discoverMore: "اكتشف المزيد",
        hello: "مرحباً",
        manageServices: "إدارة الخدمات",
        viewAllServices: "عرض جميع الخدمات",
        planAndManage: "التخطيط والإدارة",
        trackYourRequests: "تتبع طلباتك",
        
        // My Services translations
        myServicesTitle: "خدماتي",
        addService: "إضافة خدمة",
        noServices: "لا توجد خدمات",
        tapToAddNewService: "اضغط على + لإضافة خدمة جديدة",
        loadingServices: "جاري التحميل...",
        serviceType: "نوع الخدمة",
        serviceName: "اسم الخدمة",
        serviceDescription: "الوصف",
        price: "السعر",
        duration: "المدة",
        addNewService: "إضافة خدمة",
        editService: "تعديل الخدمة",
        deleteService: "حذف الخدمة",
        confirmDelete: "هل أنت متأكد من حذف",
        delete: "حذف",
        edit: "تعديل",
        active: "نشط",
        inactive: "غير نشط",
        selectServiceType: "اختر نوع الخدمة",
        serviceNameRequired: "اسم الخدمة مطلوب",
        priceRequired: "السعر مطلوب",
        durationRequired: "المدة مطلوبة",
        serviceCreated: "تم إنشاء الخدمة بنجاح",
        serviceUpdated: "تم تحديث الخدمة بنجاح",
        serviceDeleted: "تم حذف الخدمة بنجاح",
        saving: "جاري الحفظ...",
        update: "تحديث",
        add: "إضافة",
        hours: "ساعات",
        hour: "ساعة",
        days: "أيام",
        day: "يوم",
        
        // Parts Requests translations
        partsRequests: "طلبات القطع",
        allRequests: "الكل",
        pending: "قيد الانتظار",
        accepted: "مقبول",
        rejected: "مرفوض",
        completed: "مكتمل",
        all: "الكل",
        noRequests: "لا توجد طلبات",
        noRequestsDescription: "لم تقم بعمل أي طلبات قطع غيار بعد. قم بإنشاء طلبك الأول للتواصل مع الموردين.",
        createRequest: "إنشاء طلب",
        requestVisibility: "رؤية الطلب",
        views: "مشاهدات",
        suppliersViewed: "موردين شاهدوا هذا",
        interested: "مهتم",
        contactAttempts: "محاولات الاتصال",
        acceptedBySupplier: "مقبول من المورد",
        unknownSupplier: "مورد غير معروف",
        chat: "محادثة",
        estimatedDelivery: "التسليم المقدر",
        vehicle: "المركبة",
        year: "السنة",
        fuel: "الوقود",
        engine: "المحرك",
        licensePlate: "لوحة الترخيص",
        vin: "رقم الهيكل",
        color: "اللون",
        mileage: "المسافة المقطوعة",
        quantity: "الكمية",
        message: "رسالة",
        unknownPart: "قطعة غير معروفة",
        loadingRequests: "جاري تحميل الطلبات...",
        
        // Edit Profile translations
        editProfileTitle: "تعديل الملف الشخصي",
        garageProfile: "ملف الورشة",
        updateGarageInfo: "قم بتحديث معلومات ورشتك",
        basicInformation: "معلومات أساسية",
        contactInformation: "معلومات الاتصال",
        garageName: "اسم الورشة",
        managerName: "اسم المدير",
        location: "الموقع",
        contactNumber: "رقم الاتصال",
        email: "البريد الإلكتروني",
        servicesOffered: "الخدمات المقدمة",
        selectServicesDescription: "حدد الخدمات التي تقدمها ورشتك",
        saveChanges: "حفظ التغييرات",
        cancel: "إلغاء",
        fillAllFields: "يرجى ملء جميع الحقول",
        selectServices: "يرجى اختيار خدمة واحدة على الأقل",
        successProfileUpdate: "تم تحديث الملف الشخصي بنجاح!",
        profileUpdateFailed: "فشل في تحديث الملف الشخصي. حاول مرة أخرى.",
        garageNamePlaceholder: "أدخل اسم الورشة",
        managerNamePlaceholder: "أدخل اسم المدير",
        locationPlaceholder: "أدخل الموقع",
        contactPlaceholder: "أدخل رقم الاتصال",
        emailPlaceholder: "أدخل البريد الإلكتروني",
        
        // Additional translations
        confirmLogout: "هل أنت متأكد من تسجيل الخروج؟",
        spareParts: "طلب قطع غيار",
        myPartsRequests: "طلبات قطع الغيار الخاصة بي"
    }
};
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>("fr");
    const toggleLanguage = () => setLanguage(language === "fr" ? "ar" : "fr");
    return (
        <LanguageContext.Provider value={{language, setLanguage, toggleLanguage, translations}}>
            {children}
        </LanguageContext.Provider> 

    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
};